-- AI Orchestrator Phase 3: usage tracking + rate-limit cooldown memory for
-- supabase/functions/ai-router. Two tables, both written exclusively by that Edge Function's
-- service-role client — no policies or grants to authenticated on either, same reasoning as
-- impersonation_sessions (20261021000000): a plain authenticated client has no legitimate reason
-- to read or write either table directly, only through the Edge Function's own auth/role gate.
--
-- Both tables need an EXPLICIT grant to service_role: service_role has BYPASSRLS, but that only
-- bypasses row-level security — it does NOT grant table-level privileges on a newly created table.
-- This project has hit that exact gap twice already (impersonation_sessions, 20261022000000) —
-- both grants are included here from the start instead of as a follow-up fix.
begin;

-- ai_provider_state: one row per "{provider}:{model}" combination the router has ever rate-limited
-- against. cooldown_until null (or in the past) means "available, attempt it"; a future timestamp
-- means "skip this candidate without a network call until then" (see
-- supabase/functions/ai-router/taskRunner.ts's runStage and providers/cooldown.ts). Written only on
-- a genuine 429 from the provider — never touched on success or on a non-429 error.
create table public.ai_provider_state (
  id text primary key, -- '{provider}:{model}', e.g. 'groq:openai/gpt-oss-120b'
  provider text not null,
  model text not null,
  cooldown_until timestamptz,
  reason text, -- 'rpm' | 'rpd' | 'tpm' | 'unknown', or OpenRouter's own limit_source string
  last_hit_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.ai_provider_state enable row level security;
-- No policies: this table is never read or written by an authenticated client, only by
-- ai-router's own service-role client.
grant select, insert, update on public.ai_provider_state to service_role;

-- ai_usage: one row per real provider call attempt, success or failure — across both the Task
-- Registry path and the PHASE1_TEST_* diagnostic path in ai-router/index.ts — so this table
-- reflects true total usage regardless of which path made the call. A candidate skipped because it
-- was in cooldown gets no row (no network call was made).
create table public.ai_usage (
  id text primary key, -- crypto.randomUUID(), generated by providers/usageLog.ts
  provider text not null,
  model text, -- nullable: unknown when the model itself couldn't be resolved (misconfiguration)
  task text not null, -- e.g. 'CAMPAIGN_SUMMARY', or a PHASE1_TEST_* task name
  stage text, -- e.g. 'ANALYZE'; null for the PHASE1_TEST_* path (it has no stages)
  ok boolean not null,
  kind text, -- 'rate_limit' | 'error'; null when ok = true
  reason text, -- 'rpm' | 'rpd' | 'tpm' | 'unknown'; null when ok = true or not applicable
  limit_source text, -- OpenRouter-specific; null otherwise
  input_tokens integer,
  output_tokens integer,
  total_tokens integer,
  -- Gemini-only (usageMetadata.thoughtsTokenCount): captured as its own column to observe whether
  -- Gemini's thinking tokens are eating into maxOutputTokens — an unverified risk flagged at the
  -- end of Phase 2 (Google's official docs were unreachable from this project's build environment).
  thoughts_tokens integer,
  request_id text, -- one per incoming HTTP request; groups every attempt in a single fallback chain
  created_at timestamptz not null default now()
);

create index idx_ai_usage_provider_created on public.ai_usage (provider, created_at);

alter table public.ai_usage enable row level security;
-- No policies: this table is never read or written by an authenticated client, only by
-- ai-router's own service-role client (insert only — nothing in the codebase updates or deletes a
-- row once written).
grant insert on public.ai_usage to service_role;

commit;
